### PR TITLE
Threatminer Analyzer Module

### PR DESCRIPTION
**Pull request by amanjiofficial**
Single python module for all endpoints of threatminer. Please have a look @mlodic .

### CODE REVIEW

**Comment by mlodic** [comment]
Thank you.

Please adjust the code here: `threatminer.py`
line 51 -> duplicated and unused code
line 55 -> continuation line under-indented
line 63, line74 -> missing whitespace
line 72 -> rt_value could be not referenced

Please follow PEP8 code style rules. Add a PEP8 evaluator to your own IDE that can assist you in this tasks.

I'll try to update LGTM analysis configuration to let us show these mistakes next times.

**Comment by mlodic** [comment]
Thank you but again,

 line 72 -> rt_value could be not referenced

If an Intel Owl user adds a new ThreatMiner configuration, the rt_value would be undefined. The result would be the crash of the program.

**Comment by amanjiofficial** [comment]
In this PR there are 3 analyzer configurations for Threatminer API and each of them has seperate 'rt' parameter value associated with them. Could you please elaborate the case scenario where the program would crash.

**Comment by mlodic** [comment]
That's exactly the point. You cannot rely on the `analyzer_config.json` because it is a configuration and can be changed by a user. If you have read the documentation (https://intelowl.readthedocs.io/en/latest/Installation.html#analyzers-configuration), an user can change it so, referencing the analyzer names in the module is bad and it has to be changed too.

Also, if an user adds a custom analyzer for this module in the configuration, the program would crash because that `rt_value` is not initialized. And, even if this case has not any chance to happen, it is bad code practice to "rely" on a configuration file in your code. That code is broken by itself because that variable _could_ not have been initialized. It must be changed.

**Comment by amanjiofficial** [comment]
Moved to #48

**Pull request closed without merging**
