### PR TITLE
threatminer analyzer module

### PR DESCRIPTION
**Pull request by amanjiofficial**
First implementation of Threatminer module. Please have a look and suggest changes @mlodic.

### CODE REVIEW

**Comment by mlodic** [comment]
Hi @amanjiofficial, there are other problems:

-  I did not understood why you correctly joined the PDNS and the Reports Tagging in a single analyzer but, then, you created another identical analyzer for Subdomains. Could you please join both python modules in a single one?

- Also, you overwritten a previous configuration (Robtex_Forward_PDNS_Query), de facto disabling that analyzer.

**Comment by amanjiofficial** [comment]
As PDNS and Reports Tagging are defined for two observable_classification(ip and domain) whereas subdomains is defined only for one observable_classification(ip). If you prefer then I will join both python modules in single one.

**Comment by mlodic** [comment]
Nice observation. I found out that there is the same problem for `robtex_ip` and `robtex_rdns` modules. They implement almost the same thing but they splitted in 2 different modules. They should not.

In both cases, in the JSON configuration you can use the same `python_module` but with a different list in `observable_supported`. No need for different modules.

**Comment by amanjiofficial** [comment]
Okay in that case I will create a single python module for all robtex(ip,rdns,fdns) endpoints and a single python module for threatminer(subdomains, report tagging, pdns) endpoints.

**Comment by mlodic** [comment]
That would be awesome, thanks!

**Comment by amanjiofficial** [comment]
I think creating a new branch will be appropriate to avoid conflicts in the code base and ensure maintained code base.

**Comment by amanjiofficial** [comment]
I will fix for both robtex and

**Pull request closed without merging**
