### PR TITLE
single module for robtex api endpoints

### PR DESCRIPTION
**Pull request by amanjiofficial**
Followed From #29.
Robtex Analyzer integrated in a single python module
The conditions to run different endpoints of API doesn't depend on name of analyzer as suggested by @mlodic. Please review.

### CODE REVIEW

**Comment by mlodic** [comment]
Hi, as stated by the bot, please fix the "Potentially uninitialized local variable".

Also, while refactoring the tests, you removed the `robtex_rdns` test....

**Comment by amanjiofficial** [comment]
Since there is a single module for robtex, thus having different test for same observable classification is redundant unless we modify to test for different robtex endpoints. IF you still prefer then I will add test for robtex_rdns.

**Comment by mlodic** [comment]
It is not a matter of preferences, you just removed the test for the `Robtex_Reverse_PDNS_Query` analyzer. Without it we cannot test if that analyzer does work or not. You have to just rename that part, not removing it.

**Comment by amanjiofficial** [comment]
@mlodic suggested changes pushed.

**Comment by mlodic** [comment]
You fixed the mistake correctly but the log message is wrong. You copied and pasted...

**Pull request merged**
