### PR TITLE
Added integration for HoneyDB API - /nodes endpoint

### PR DESCRIPTION
**Pull request by Eshaan7**
Added the integration for HoneyDB's `api/nodes` endpoint as requested in PR - https://github.com/certego/IntelOwl/pull/20.

### CODE REVIEW

**Comment by mlodic** [comment]
Thank you again.

However you can achieve the same result without creating 2 different python modules but with a single one.

You can manage this with a variable in "additional_param_config"  that allow you to choose which endpoint you have to query with the selected observable.

Please try to follow this configuration to avoid redundant code.

**Comment by Eshaan7** [comment]
Alright. I'll make the necessary changes.

**Comment by mlodic** [comment]
Hi @Eshaan7, could you also please remove commits like "fix merge commits" or anything else related to fixes caused by the broken history on your branch? Otherwise you would poison the history in the master when the pull request will be accepted. Thank you

**Comment by mlodic** [comment]
A guide on how to squash commits: https://github.com/wprig/wprig/wiki/How-to-squash-commits.

**Comment by Eshaan7** [comment]
Hi, I have had to create a new branch and thus a new PR as this one had become messy. Hope that's alright. Please take a look at #24.

**Pull request closed without merging**
